name: keep_healthy
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

  bloc: ^0.14.0
  flutter_bloc: ^0.20.0
  flutter_local_notifications: ^0.8.0
  equatable: ^0.1.5
  shared_preferences: ^0.5.3+4
  intl: ^0.15.8
  flutter_datetime_picker: ^1.2.5
  toast: ^0.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
